- name: Install K3s on the controlplane01
  hosts: controlplane01
  become: true # To run the installation as a privileged user
  vars:
    k3s_install_url: "https://get.k3s.io"
    k3s_exec_options: "server --cluster-init --write-kubeconfig-mode '644' --disable=traefik --disable-network-policy --disable=servicelb --disable=local-storage --flannel-backend none --disable-helm-controller"

  tasks:
    - name: Install K3s (curl and execute with specific options)
      shell: |
        curl -sfL {{ k3s_install_url }} | INSTALL_K3S_EXEC="{{ k3s_exec_options }}" sh -
      args:
        creates: "/usr/local/bin/k3s"
      become: true
      become_user: root

    - name: Verify K3s installation
      command: /usr/local/bin/k3s --version
      register: k3s_version
      changed_when: false

    - name: Show K3s version
      debug:
        msg: "K3s version installed: {{ k3s_version.stdout }}"
